-- MySQL Script generated by MySQL Workbench
-- Fri Jul 24 10:43:34 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema color_database
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema color_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `color_database` DEFAULT CHARACTER SET utf8mb3 ;
USE `color_database` ;

-- -----------------------------------------------------
-- Table `color_database`.`hex_values`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `color_database`.`hex_values` ;

CREATE TABLE IF NOT EXISTS `color_database`.`hex_values` (
  `color_id` INT NOT NULL AUTO_INCREMENT,
  `hex` VARCHAR(7) NOT NULL,
  `compliment` VARCHAR(7) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `image_path` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`color_id`),
  UNIQUE INDEX `color_id_UNIQUE` (`color_id` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 165
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
